title: AmanithVG
description: OpenVG 1.1 library for 2D vector graphics rendering
description2: 
google_analytics: 
copyright: (C) 2005-2017 Mazatech, S.r.l.
vatid: VAT ID IT03498460405
rights: All rights reserved
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  sass_dir: _includes
  style: compressed
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
