title: AmanithVG
description: OpenVG 1.1 library for 2D vector graphics rendering
description2: 
url: https://www.amanithvg.com
enforce_ssl: www.amanithvg.com
google_analytics: UA-257732-1
copyright: (C) 2018 Mazatech, Srl
vatid: VAT ID IT03498460405
rights: All rights reserved
collections:
  docs:
    output: true
assets:
  sources:
    - _assets
    - _assets/fonts
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  sass_dir: _includes
  style: compressed
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
plugins: 
  - jekyll-sitemap
